### ISSUE TITLE
SoapUI: The security token could not be authenticated or authorized

### ISSUE THREAD

**Issue by mortenberg80** [difi/kontaktregisteret-klient#10]
Hei,

Jeg prøver å kjøre SoapUI-prosjektet mot https://kontaktinfo-ws-ver2.difi.no/kontaktinfo-external/ws-v5

Jeg har følgende oppsett:
Mac OS X
SoapUI 4.5.1
Java 1.7.0_51 med JCE

Jeg sjekker ut SoapUI-prosjektet, importerer det i SoapUI og oppdaterer lokasjonen til keystoren. Så prøver jeg å kjøre begge requestene som ligger inne for HentPersoner, men begge feiler med meldingen "The security token could not be authenticated or authorized". Er noen av sertifikatene i keystoren utløpt/byttet, eller er det noe annet jeg gjør galt?

mvh
Morten

**Comment by joergenb** [comment]
Har du sjekka ut "master" eller "version_5" branchen?  Eg ser vi har nyere endringer i version_5-branchen, som ikkje er blitt merga tilbake til master...

**Comment by mortenberg80** [comment]
Hei,

Dette er på VERSION_5-branchen, med .jks'en som er der. Vedlagt er det jeg mener blir sendt av SoapUI.
[v5-request.txt](https://github.com/difi/kontaktregisteret-klient/files/229841/v5-request.txt)

**Comment by mortenberg80** [comment]
Jeg prøver også å kjøre maven-bygget som kjører java-klienten, men de 4 testene der feiler også med det samme.

**Comment by aamundbr** [comment]
Hei.

Klarer å gjenskape samme feil. Det er klienten som ikkje klarer å verifisere signatur på respons. Skyldes ant.vis problemer sertifikatkonfigurasjon i VER-miljøa. Problemet er meldt vidare til dei som er ansvarlige for applikasjonsdrifta, så forhåpentlig vis vil det bli løst ganske fort.

**Comment by aamundbr** [comment]
Dette skal vere rydda opp i nå. Bruk eksempelkode fra master-branch. Lukker denne saka.
