### ISSUE TITLE
Reference to test data

### ISSUE THREAD

**Issue by codingchili** [difi/kontaktregisteret-klient#11]
Hello,

Where can i find a list of persons that exists in the test environment register? I found a few in the test classes but none seems to include phone numbers, only email addreses. 

Regards

**Comment by eirikhoem** [comment]
Hi. Could you send this question to idporten@difi.no<mailto:idporten@difi.no> – and we’ll help you

Eirik Hoem

Fra: Robin Duda [mailto:notifications@github.com]
Sendt: torsdag 5. oktober 2017 13.29
Til: difi/kontaktregisteret-klient <kontaktregisteret-klient@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [difi/kontaktregisteret-klient] Reference to test data (#11)


Hello,

Where can i find a list of persons that exists in the test environment register? I found a few in the test classes but none seems to include phone numbers, only email addreses.

Regards

**Comment by codingchili** [comment]
thanks!

**Comment by codingchili** [comment]
Reopening this issue as I was not able to receive a response to my email. In response, idporten@difi.no referred me to another email address, Which is yet to respond.

**Comment by codingchili** [comment]
Finally received a list of persons, unfortunately only one of them is registered in the test environment.
```
 01022349836 
 01022349917 
 01022400211
 01022434221 
 01022435368 
 01022435791 
 01022437107 
 01022440949
 01022447250 
 01022447684
 01022448044
```

Thanks for the help.
