### ISSUE TITLE
Test certificate expired

### ISSUE THREAD

**Issue by mlidal** [difi/kontaktregisteret-klient#14]
Hello. 

We have a service based on this client and I just noticed that the service has started failing in test. Checking the certificate in kontaktinfo-client-test.jks I see that it expired June 12. Can you update the test-certificate?

**Comment by aamundbr** [comment]
Hi, sorry for late reply.

Certificate and some dependencies are updated. If you are running this as a permanent installation in test, you should consider to acquire a test certificate issued to your own organization.

Please also consider to change your integration to the REST API - https://samarbeid.difi.no/nyhet/2019/08/viktig-informasjon-om-tilgang-til-kontakt-og-reservasjonsregisteret-gjennom-soap-grensesnitt
