### ISSUE TITLE
.Net klienten virker ikke mot ws-v4

### ISSUE THREAD

**Issue by trygu** [difi/kontaktregisteret-klient#7]
Har testet litt med .Net-koden mot KRR (og default endepunkt der er ws-v3). Når jeg bruker default sertifikatene som følger med koden gir den en SOAP-feil:

    Could not validate Virksomhetsertifikat;  Could not verify security header key element

Hjelper ikke å legge inn gyldig virksomhetssertifikat heller.

**Comment by eirikhoem** [comment]
.NET-klienten støtter bare versjon 3.

For øyeblikket er det bare testklienten i Java som støtter versjon 4.

Det for øyeblikket uvist om, og når Difi kan tilby en .NET-klient som støter versjon 4. Det vil trolig komme avklaringer rundt dette om ikke lang tid.

**Comment by aberner** [comment]
Endringene fra versjon 3 til versjon 4 er kun på WS-Security, selve metodekallene er helt like.
Så håper at informasjonen under er til hjelp og at du dermed kanskje kan modifisere denne klienten og bidra til å oppgradere .Net klient eksemplet til å støtte versjon 4. Ellers så jobber vi i Difi med å få det oppgradert men det er usikkert når dette vil bli realisert.


**Endringen fra v3 til v4**

* Heile sertifikatet må sendast inn som ein del av requesten. 
** Dette må gjerast ved bruk av KeyIdentifier elementet med Encoding «Base64Binary» og ValueType «X509v3», ref. WSS X.509 certificate token profile (http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0 ). 
* Timestamp i request må vere signert
* Symmetrisk krypteringsnøkkel i respons er endra til «http://www.w3.org/2001/04/xmlenc#aes256-cbc»
* Transportalgoritme for symmetrisk krypteringsnøkkel i respons er endra til «http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p»

**Comment by pereilif** [comment]
Hei,

Hvordan ligger det an med å få en eksempel .NET-klient som støtter versjon 4?

**Comment by joergenb** [comment]
Hei,
Utvikling av .NET klient for v4 er i ferd med å bli sluttført, så vi tar sikte på å kunne publisere denne ila. noen få uker.

**Comment by aberner** [comment]
@pereilif vi har nå laget et eget bibliotek for .net som støtter versjon 4. Dette ligger her: https://github.com/difi/oppslagstjeneste-klient-dotnet med tilhørende dokumentasjon her: http://difi.github.io/oppslagstjeneste-klient-dotnet/
