### ISSUE TITLE
Bruk av .net klienten mot v4

### ISSUE THREAD

**Issue by austrheim** [difi/kontaktregisteret-klient#8]
Hei.

Bare en avklaring som egentlig gjelder .net klientbiblioteket (postet der også https://github.com/difi/oppslagstjeneste-klient-dotnet/issues/19 ):

Fungerer klienten mot v4 nå?

I "hurtigguide_for_integrasjon_mot_oppslagstjenesten_2015.02.03.pdf" står det følgende:

> * .NET-klient (kun v3)

Er dette fortsatt korrekt?

**Comment by eirikhoem** [comment]
Hei, ja klienten fungerer mot v4 nå. 

Det ligger en lett revidert hurtigguide på https://samarbeid.difi.no/kontakt-og-reservasjonsregisteret/dokumentasjon (datert 17.08.15)
