### ISSUE TITLE
The signature or decryption was invalid when running tests

### ISSUE THREAD

**Issue by iko3** [difi/kontaktregisteret-klient#9]
When running the tests in "kontaktinfo-app-wsclient-sample" I get "The signature or decryption was invalid" error:
org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor handleMessage
WARNING: 
org.apache.ws.security.WSSecurityException: The signature or decryption was invalid

**Comment by aamundbr** [comment]
Hi.

Is the root cause of the exception "java.security.InvalidKeyException: Illegal key size" ?

You need to install JCE Unlimited Strength to run the tests. See http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html for Java 8 downloads...

**Comment by iko3** [comment]
thank you, that solved the problem ;)
